apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-node-provider-files
  labels:
    app.kubernetes.io/name: traffic-node-provider
    app.kubernetes.io/part-of: traffic-counter
data:
  remote_whitelist.txt: |-
    # Example prefixes to ignore
    10.0.0.0/8
    192.168.0.0/16
