[package]
name = "node-provider"
version = "0.0.0-alpha"
edition.workspace = true

license.workspace = true

[dependencies]
tokio-stream = "0.1"
tonic = { version = "0.11", features = ["transport"] }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true, default-features = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "signal",
] }
libc = { workspace = true }
api = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
rtnetlink = "0.20"
netlink-packet-route = "0.28"
futures = "0.3"

[[bin]]
name = "node-provider"
path = "src/main.rs"
