apiVersion: v1
kind: Service
metadata:
  name: traffic-counter
  labels:
    app.kubernetes.io/name: traffic-counter
    app.kubernetes.io/part-of: traffic-counter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traffic-counter
    app.kubernetes.io/part-of: traffic-counter
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
