syntax = "proto3";

package trafficcounter.v1;

message HttpMeta {
  string host_ip = 1;
  string client_ip = 2;
  string host = 3;
}

message L4Meta {
  string local_ip = 1;
  string remote_ip = 2;
  uint32 local_port = 3;
  uint32 remote_port = 4;
  string protocol = 5;
}

message HttpGatewayTraffic {
  HttpMeta http_meta = 1;
  uint64 request_bytes = 3;
  uint64 response_bytes = 4;
}

message NodePortTraffic {
  L4Meta l4_meta = 1;
  uint64 rx_bytes = 3;
  uint64 rx_packets = 4;
  uint64 tx_bytes = 5;
  uint64 tx_packets = 6;
}

message ClusterTraffic {
  L4Meta l4_meta = 1;
  uint64 rx_bytes = 3;
  uint64 rx_packets = 4;
  uint64 tx_bytes = 5;
  uint64 tx_packets = 6;
}

message Traffic {
  oneof kind {
    HttpGatewayTraffic http_gateway = 1;
    NodePortTraffic node_port = 2;
    ClusterTraffic cluster = 3;
  }
}

message IngestTrafficRequest {
  Traffic traffic = 1;
}

message IngestTrafficResponse {}

service TrafficIngestor {
  rpc IngestTraffic(IngestTrafficRequest) returns (IngestTrafficResponse);
}
